language: c
compiler: gcc
sudo: required
addons:
    apt:
        packages:
            - ubuntu-dev-tools
            - dput
            - debhelper
            - fakeroot
            - pkg-kde-tools

matrix:
    include:
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-xenial-gcc

script:
    - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-xenial-gcc"   ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
    - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-xenial-clang" ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi

after_success:
    - ${TRAVIS_BUILD_DIR}/misc/ci-scripts/packaging.sh

deploy:
    provider: script
    skip_cleanup: true
    on:
        all_branches: true
    script:
        - cat ${TRAVIS_BUILD_DIR}/misc/ci-scripts/deploy-launchpad.sh
