language: c
compiler: gcc
sudo: required
addons:
    apt:
        packages:
            - ubuntu-dev-tools
            - dput
            - debhelper
            - fakeroot

matrix:
    include:
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-xenial-gcc
        - os: linux
          env: TARGET_ENVIRONMENT=ubuntu-xenial-clang

script:
  - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-xenial-gcc"   ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
  - if [[ "$TARGET_ENVIRONMENT" == "ubuntu-xenial-clang" ]]; then docker build --rm -t ${TARGET_ENVIRONMENT} -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT} . ; fi
