language: c
compiler: gcc
sudo: required
addons:
    apt:
        packages:
            - ubuntu-dev-tools
            - dput
            - debhelper
            - fakeroot
            - pkg-kde-tools

matrix:
    include:
        - os: linux
          env:
              - TARGET_DISTROS=xenial
              - TARGET_ENVIRONMENT=ubuntu-xenial
        - os: linux
          env:
              - TARGET_DISTROS=trusty
              - TARGET_ENVIRONMENT=ubuntu-trusty

script:
    - docker build --rm -t ${TARGET_ENVIRONMENT}-gcc -f misc/docker/Dockerfile-${TARGET_ENVIRONMENT}-gcc .

after_success:
    - ${TRAVIS_BUILD_DIR}/misc/ci-scripts/packaging.sh

deploy:
    provider: script
    skip_cleanup: true
    on:
        all_branches: true
    script:
        - cat ${TRAVIS_BUILD_DIR}/misc/ci-scripts/deploy-launchpad.sh
