language:
  - cpp
compiler:
  - gcc
env:
  global:
   - secure: "gZmz5LLE3wOQiRJemhJpVd/eI0A3GR4ZByxMJtMhmnS+eCDQ5x1IXBQFXMpsi6ZM+w9OT7Gro4l2AuPzag+J2Bgh4zsGoHlrkreMoL3HM8IguQjg/tA2WlVXWE6WykzIe0xBj4cPMthx/RwCtAXdcGk316xWsJ3L89Y5+5eqhdv9QOQXERSFoJ9cYKRUugncCI2PxFEKW97Mi1lRqaTRWvj1rWUSMnaIkvGczQdf4sKkHIRghhs1z5ouN6oNOSW88W7MtAJJ/V6G1BmrLgbCyAhBSkRXHVIeRxlc/Q61Am0UZtwVXEh3XfVBuwpuXzC56+X3bUjdjS2qBrafQEZaqODt0i1y78nB7BBtmIV4qK4V1lKPUjvvCfGFZyVD1celevQxpuNKdJpeSeaRCk0cziF/OnM/+hq9+Sb5lh5BzTZwjqQ1RVPSrXASq5ypDRU4aFZ5KMfRbU0HqkWZSCljZPpptchV9+JFoYQoqnos8NhcryMU9S1Ck28LKMbmPr1g3C6FI1R+mt68fh/t/2y7WSo18WeFNItaSuoi/fv20VY1EjhOXnilzBmwRe6+vn3mSn4H0C7HKiPjBrFtv9vVzHFNA9K2R5cTVUTc2vMAQgpwf6EPCh7Kw6ZoC1QOtusa6bfiK3OmXpkXn3ee2atqZ+8xyiYdCcVsT5ezJqNg5d8="
script: source .travis.sh
after_success:
  - set +x
  - export GIT_COMMITTER_NAME=$GIT_NAME
  - export GIT_COMMITTER_EMAIL=$GIT_EMAIL
  - export GIT_AUTHOR_NAME=$GIT_NAME
  - export GIT_AUTHOR_EMAIL=$GIT_EMAIL
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
